apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-nginx
spec:
  action: pod-kill
  mode: one
  duration: '60s'
  selector:
    labelSelectors:
      "app": "nginx"
  scheduler:
    cron: "@every 2m"

