apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-deployment
  labels:
    project: spring-prod-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      project: spring-pod-demo
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        project: spring-pod-demo
    spec:
      containers:
        - name: spring-petclinic
          image: springcommunity/spring-framework-petclinic:5.3.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80 
    targetPort: 8080 
  selector:
    project: spring-pod-demo
