apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport-spring-petclinic
spec:
  type: LoadBalancer
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      protocol: TCP
      targetPort: 8080 # Container Port
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
  selector:
    project: spring-pod-demo
# Reference: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
---
### Create Deployments
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-deployment
  labels:
    project: spring-prod-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      project: spring-pod-demo
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        project: spring-pod-demo
    spec:
      containers:
        - name: spring-petclinic
          image: dockerbikram/spring-petclinic:3.2.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: "15Mi"
              cpu: "5m"
            limits:
              memory: "20Mi"
              cpu: "5.5m"
          ports:
            - containerPort: 8080
