# single-container-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.25.3
      imagePullPolicy: Always
      ports:
        - containerPort: 80
